package Main;


import AccountManagement.AccountManagementPage;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author niebz
 */
public class LoginPage extends javax.swing.JFrame {



    /**
     * Creates new form LoginPage
     */

    public LoginPage() {



        initComponents();
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).
        put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Cancel");

        getRootPane().getActionMap().put("Cancel", new AbstractAction()
        {
            public void actionPerformed(ActionEvent e)
            {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        text_id = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("RSU", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        text_password.setFont(new java.awt.Font("RSU", 0, 18)); // NOI18N
        text_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_passwordKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("RSU", 0, 18)); // NOI18N
        jLabel2.setText("Username :");

        jLabel3.setFont(new java.awt.Font("RSU", 0, 18)); // NOI18N
        jLabel3.setText("Password :");

        loginBtn.setFont(new java.awt.Font("RSU", 0, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registerBtn.setFont(new java.awt.Font("RSU", 0, 14)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("RSU", 0, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        text_id.setFont(new java.awt.Font("RSU", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(text_password, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(text_id))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(loginBtn)
                    .addComponent(exitBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Your ID is : "+currentid());
        Login();// เรียกใช้ Method Login เพื่อเข้าสู่ระบบ

    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        RegisterForm rf = new RegisterForm(this,false); // สร้าง Object จากคลาส RegisterForm
        rf.setVisible(true); // เรียกใช้ Object ที่สร้างเพื่อให้แสดงขึ้นมา

    }//GEN-LAST:event_registerBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0); // สั่งออกจากโปรแกรมเมื่อกดปุ่ม Exit
    }//GEN-LAST:event_exitBtnActionPerformed

    private void text_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Login(); // เมื่อ Cursor ชี้อยู่ที่ password_TextField สามารถกดปุ่ม Enter เพื่อ Login ได้
    }//GEN-LAST:event_text_passwordKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int lebar = this.getWidth()/2;
        int tinggi = this.getHeight()/2;
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-lebar;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-tinggi;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }
    

    // ------------------------------------Method ที่ใช้ในการ Login เข้าสู่หน้า Menu-----------------------------------
    private void Login(){
        String id = text_id.getText(); // เก็บข้อมูล String ที่ได้จาก TextField
        char[] temp = text_password.getPassword(); // เก็บข้อมูลรหัสผ่านที่ได้จาก PasswordField
        String password = String.valueOf(temp); // แปลงรหัสผ่านเป็นข้อมูลประเภท String เพื่อง่ายต่อการทำงาน

        // ---------------↓ ↓ ↓ ↓-----เมื่อทำงานกับ Database ต้องใช้ try catch เพื่อป้องกันข้อผิดพลาด------↓ ↓ ↓ ↓---------------------
        try {
            DB_Connection db = new DB_Connection(); // สร้าง Object เพื่อเรียกใช้คำสั่งที่ทำงานร่วมกับ Database

            //  ↓ ↓ ↓ ↓คำสั่ง Sql เพื่อเช็กว่ามีข้อมูล ID และ Password ที่รับเข้ามาใน Database หรือไม่ ↓ ↓ ↓ ↓
            String query = String.format("SELECT * FROM customers WHERE customer_id='%s' AND customer_password='%s'",id,password);
            //  ↑ ↑ ↑ ↑คำสั่ง Sql เพื่อเช็กว่ามีข้อมูล ID และ Password ที่รับเข้ามาใน Database หรือไม่ ↑ ↑ ↑ ↑

            ResultSet rs = db.getResultSet(query); // สั่ง execute query และเก็บผลลัพที่ได้จากการ excecute ไว้ใน ResultSet

            if (rs.next()) { // เช็กว่าใน ResultSet มีข้อมูลหรือไม่ ถ้ามีจะ return ค่าออกมาเป็น ture
                // คำสั่งต่อไปนี้จะทำก็ต่อเมื่อ Username และ Password ถูกต้อง (มีอยู่ใน Database) เท่านั้น
                this.setVisible(false); // สั่งซ่อนหน้า Login ที่ไม่สั่ง Dispose เพราะมีการเรียกใช้ข้อมูลจากหน้า Login ภายตัวโปรแกรม
                Method.displayInfo("You are logging in");// แสดงกล่องข้อความว่า Login สำเร็จ
                MenuPage mn = new MenuPage(); // สร้าง Object จากหน้า Menu
                mn.setVisible(true); // สั่งแสดงหน้า Menu
            }else{
                // คำสั่งต่อไปนี้จะทำก็ต่อเมื่อ Username และ Password ไม่ถูกต้อง (ไม่มีอยู่ใน Database) เท่านั้น
                Method.displayError("Username or password is wrong!");
                text_password.setText(null);
            }
        } catch (SQLException e) {// สั่งเก็บข้อผิดความที่ก็ขึ้นไว้ใน e
            // คำสั่งต่อไปนี้จะทำก็ต่อเมื่อเกิดข้อผิดพลาดจากคำสั่งภายใน try เท่านั้น
            Method.displayError("Error : "+e);// สั่งให้แสดงกล่องข้อความเพื่อแสดงข้อผิดพลาดที่เกินดึ้น
        }
        // ------------↑ ↑ ↑ ↑------เมื่อทำงานกับ Database ต้องใช้ try catch เพื่อป้องกันข้อผิดพลาด------↑ ↑ ↑ ↑--------------------
    }
    // -------------------------------------------------------------------------------------------------------


    // -----Method ที่จะ retrun Username ที่ใช้โปรแกรมอยู่ในขณะนั้น-----
    public static String currentid(){
        return text_id.getText();
    }
    // -------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton registerBtn;
    private static javax.swing.JTextField text_id;
    private javax.swing.JPasswordField text_password;
    // End of variables declaration//GEN-END:variables
}
