package Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

import Main.DB_Connection;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author niebz
 */
public class view_statement extends javax.swing.JDialog {

    /**
     * Creates new form view_statement
     */

    static String selectedStmId = null;
    static String selectedStmDate = null;
    static String selectedStmType = null;
    static String selectedStmAmount = null;
    static String ac_number_recipiebt = null;
    public view_statement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refresh_view_ac_btn = new javax.swing.JButton();
        back_view_ac_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        view_stm_pane = new javax.swing.JScrollPane();
        view_stm_table = new javax.swing.JTable();
        ac_number_label = new javax.swing.JLabel();
        view_detail_stm_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        refresh_view_ac_btn.setText("Refresh");
        refresh_view_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_view_ac_btnActionPerformed(evt);
            }
        });

        back_view_ac_btn.setText("Back");
        back_view_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_view_ac_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Statement of account number :");

        view_stm_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        view_stm_pane.setViewportView(view_stm_table);

        ac_number_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ac_number_label.setText("###############");

        view_detail_stm_btn.setText("View detail");
        view_detail_stm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_detail_stm_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(view_detail_stm_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refresh_view_ac_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(back_view_ac_btn))
                        .addComponent(view_stm_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ac_number_label, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ac_number_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view_stm_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh_view_ac_btn)
                    .addComponent(back_view_ac_btn)
                    .addComponent(view_detail_stm_btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh_view_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_view_ac_btnActionPerformed
        // TODO add your handling code here:
        setTable();
    }//GEN-LAST:event_refresh_view_ac_btnActionPerformed

    private void back_view_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_view_ac_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_back_view_ac_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ac_number_label.setText(StatementPage.ac_number);
        setTable();

    }//GEN-LAST:event_formWindowOpened

    private void view_detail_stm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_detail_stm_btnActionPerformed
        // TODO add your handling code here:

        selectedStmId = view_stm_table.getValueAt(view_stm_table.getSelectedRow(),1).toString();
        selectedStmDate = view_stm_table.getValueAt(view_stm_table.getSelectedRow(),2).toString();
        selectedStmType = view_stm_table.getValueAt(view_stm_table.getSelectedRow(),3).toString();
        selectedStmAmount = view_stm_table.getValueAt(view_stm_table.getSelectedRow(),4).toString();

        try {
            DB_Connection db = new DB_Connection();
            String query = String.format("SELECT ac_number_recipiebt AS recipiebt FROM moneytransfer AS TF " +
                    "INNER JOIN total_statement AS TS ON TF.tf_id = TS.banking_id " +
                    "WHERE TS.stm_id = '%s';",selectedStmId);
            ResultSet rs = db.getResultSet(query);
            rs.next();
            ac_number_recipiebt = rs.getString(1);

        }catch (Exception e){

        }

        if (selectedStmType.equals("Transfer")){
            view_detail_stm_trans view_detail_stm_trans = new view_detail_stm_trans(null,false);
            view_detail_stm_trans.setVisible(true);
        }else{
            view_detail_stm view_detail_stm = new view_detail_stm(null,false);
            view_detail_stm.setVisible(true);
        }

    }//GEN-LAST:event_view_detail_stm_btnActionPerformed

    /**
     * @param args the command line arguments
     */

    private void setTable(){
        String[] row = {"#","Statement ID","Date","Type","Amount"};
        DefaultTableModel modal = new DefaultTableModel(row,0);

        String query = String.format("SELECT stm_id, stm_date, BT.type_name, amount FROM total_statement AS TS " +
                "INNER JOIN banking_type AS BT ON TS.type_id = BT.type_id " +
                "INNER JOIN account AS AC ON TS.ac_number = AC.ac_number " +
                "WHERE TS.ac_number = '%s' " +
                "ORDER BY stm_id;",StatementPage.ac_number);

        int i = 0;
        try{

            DB_Connection db = new DB_Connection();
            ResultSet rs = db.getResultSet(query);
            while(rs.next()) {
                i++;
                String stm_id = rs.getString(1);
                String stm_date = rs.getString(2);
                String type = rs.getString(3);
                String amount = rs.getString(4);
                String[] rows = {String.valueOf(i),stm_id,stm_date,type,amount};

                modal.addRow(rows);
            }
            db.disconnect();
            view_stm_table.setModel(modal);

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error : "+e);
        }


    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                view_statement dialog = new view_statement(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ac_number_label;
    private javax.swing.JButton back_view_ac_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton refresh_view_ac_btn;
    private javax.swing.JButton view_detail_stm_btn;
    private javax.swing.JScrollPane view_stm_pane;
    private javax.swing.JTable view_stm_table;
    // End of variables declaration//GEN-END:variables
}
