/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package AccountManagement;

import Main.DB_Connection;
import Main.LoginPage;
import Main.Method;
import java.awt.Toolkit;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author niebz
 */
public class close_ac extends javax.swing.JDialog {

    /**
     * Creates new form close_ac
     */
    public close_ac(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        refresh_view_ac_btn = new javax.swing.JButton();
        back_view_ac_btn = new javax.swing.JButton();
        view_ac_pane = new javax.swing.JScrollPane();
        view_ac_table = new javax.swing.JTable();
        close_ac_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("RSU", 1, 36)); // NOI18N
        jLabel1.setText("Close an account");

        refresh_view_ac_btn.setFont(new java.awt.Font("RSU", 0, 14)); // NOI18N
        refresh_view_ac_btn.setText("Refresh");
        refresh_view_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_view_ac_btnActionPerformed(evt);
            }
        });

        back_view_ac_btn.setFont(new java.awt.Font("RSU", 0, 14)); // NOI18N
        back_view_ac_btn.setText("Back");
        back_view_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_view_ac_btnActionPerformed(evt);
            }
        });

        view_ac_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        view_ac_pane.setViewportView(view_ac_table);

        close_ac_btn.setFont(new java.awt.Font("RSU", 0, 14)); // NOI18N
        close_ac_btn.setText("Close an account");
        close_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_ac_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(view_ac_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(close_ac_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresh_view_ac_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back_view_ac_btn)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(view_ac_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh_view_ac_btn)
                    .addComponent(back_view_ac_btn)
                    .addComponent(close_ac_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh_view_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_view_ac_btnActionPerformed
        // TODO add your handling code here:
        setTable();
    }//GEN-LAST:event_refresh_view_ac_btnActionPerformed

    private void back_view_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_view_ac_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_back_view_ac_btnActionPerformed

    private void close_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_ac_btnActionPerformed
        // TODO add your handling code here:

        String query;
        String ac_number;
        boolean temp;
        try {

            ac_number = view_ac_table.getValueAt(view_ac_table.getSelectedRow(),1).toString();
            int select = JOptionPane.showInternalConfirmDialog(null,"You want to close account number : "+ac_number+" ?","",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if( select == JOptionPane.YES_OPTION){

                DB_Connection db = new DB_Connection();
                query = String.format("DELETE FROM total_statement WHERE ac_number='%s';",ac_number);
                temp = db.execute(query);

                query = String.format("DELETE FROM moneywithdraw WHERE ac_number='%s';",ac_number);
                temp = db.execute(query);

                query = String.format("DELETE FROM moneytransfer WHERE ac_number_treansferor ='%s';",ac_number);
                temp = db.execute(query);

                query = String.format("DELETE FROM moneytransfer WHERE ac_number_recipiebt  ='%s';",ac_number);
                temp = db.execute(query);

                query = String.format("DELETE FROM moneydeposit WHERE ac_number='%s';",ac_number);
                temp = db.execute(query);

                query = String.format("DELETE FROM account WHERE ac_number='%s';",ac_number);
                temp = db.execute(query);

            }else throw new Exception();

        }catch (Exception e) {
            temp = false;
        }

        if(temp){
            Method.displayInfo("Success");
            setTable();
        }else{
            Method.displayError("Fail");
        }

    }//GEN-LAST:event_close_ac_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setTable();
        int lebar = this.getWidth()/2;
        int tinggi = this.getHeight()/2;
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-lebar;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-tinggi;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(close_ac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(close_ac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(close_ac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(close_ac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                close_ac dialog = new close_ac(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void setTable() {

        String current_id = LoginPage.currentid();
        String query = String.format("SELECT ac_number, Bank.bank_name, ac_name, ac_balance FROM Account INNER JOIN Bank ON Account.bank_id = Bank.bank_id WHERE customer_id='%s';",current_id);
        String[] fieldName = {"#","Number","Bank","Name","Balance"};
        DefaultTableModel model = new DefaultTableModel(fieldName,0);

        try {
            DB_Connection db = new DB_Connection();
            ResultSet rs = db.getResultSet(query);

            int i=0;
            while (rs.next()) {
                i++;
                String rownumber = String.valueOf(i);
                String ac_number = rs.getString("ac_number");
                String bank_id = rs.getString("bank_name");
                String ac_name = rs.getString("ac_name");
                String ac_balance = (rs.getString("ac_balance")+" ฿");
                String[] row = {rownumber,ac_number, bank_id, ac_name, ac_balance};

                model.addRow(row);
            }
            db.disconnect();

        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : "+e);
        }

        view_ac_table.setModel(model);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_view_ac_btn;
    private javax.swing.JButton close_ac_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton refresh_view_ac_btn;
    private javax.swing.JScrollPane view_ac_pane;
    private javax.swing.JTable view_ac_table;
    // End of variables declaration//GEN-END:variables
}
